init:
  - git config --global core.autocrlf input

build_script:
  - cmd: build.cmd

test: off

platform:
  - x64

configuration:
  - Debug

matrix:
  fast_finish: true

version: 0.0.1.{build}

cache:
  - packages -> paket.lock