init:
  - git config --global core.autocrlf input

build_script:
  - cmd: build.cmd BuildApp
  - cmd: build.cmd UnitTests
  - ps: |
    $wc = New-Object 'System.Net.WebClient'
    $wc.UploadFile("https://ci.appveyor.com/api/testresults/xunit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\xunit2.xml))

test: off

platform:
  - x64

configuration:
  - Debug

matrix:
  fast_finish: true

version: 0.0.1.{build}

cache:
  - packages -> paket.lock