init:
  - git config --global core.autocrlf input

build_script:
  - set PDFTOXMLEXE=%APPVEYOR_BUILD_FOLDER%\packages\pdf2xml\bin\pdf2xml.exe
  - build.cmd BuildApp
  - build.cmd UnitTests
  - ps: (New-Object 'System.Net.WebClient').UploadFile("https://ci.appveyor.com/api/testresults/xunit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\xunit2.xml))

test: off

platform:
  - x64

configuration:
  - Debug

matrix:
  fast_finish: true

version: 0.0.1.{build}

cache:
  - packages -> paket.lock

# on_finish:
#   - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
